spring.application.name=medicenter

spring.datasource.url=jdbc:mysql://localhost:3306/medicenter
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true